### ISSUE TITLE
New Content Type: Source

### ISSUE THREAD

**Issue by kaerumy** [Sinar/popolo.contenttypes#5]
For many of the Popolo types there is a list field for Sources. This is basically a link.

Subclass base Plone Link content type for this first.

It's the same, but we might want to add some custom views or use reference it in a relation field vs the default Link type.

**Comment by kaerumy** [comment]
Or we can make a simple class with Title, Description and URI

**Comment by JustineSurGithub** [comment]
Is there something more we want to do with the source or a reason to add a new content type for it? Else I think the basic link as in the doc is exactly what we want: https://docs.plone.org/working-with-content/adding-content/adding-links.html has Title, Description and URI...

**Comment by kaerumy** [comment]
Yes. The reason to subclass ILink was that was the same fields, but I
wanted to duplicate a feature in Popit, in which a Source also has a field
that referenced the field in parent object, so that we can query Source(s)
for a field in a parent object.
